### ISSUE TITLE
[Errno 2] No such file or directory

### ISSUE THREAD

**Issue by mikomize** [clemos/haxe-sublime-bundle#117]
i have got haxe installed via homebrew and ive set settings in sublime:

{
"haxe_path": "/usr/local/opt/haxe/bin/haxe",
"haxe_library_path": "/usr/lib/haxe/lib/"
}

and while trying to build project im getting error:

[Errno 2] No such file or directory
[cmd:  [u'haxe', u'build.hxml']]
[dir:  /Users/miko/projects/haxenode]
[path: /usr/bin:/bin:/usr/sbin:/sbin]
[Finished]

typing "/usr/local/opt/haxe/bin/haxe build.hxml" in console works fine. What am i doing wrong?

**Comment by Gaen** [comment]
Sublime native build is still not working on OSX because of homebrew and $PATH stuff, I don't want to fix it through messing with os settings. So I hacked the package itself:

* Close Sublime
* Go to `~/Library/Application Support/Sublime Text 3/Installed Packages`
* Rename Haxe.sublime-package to Haxe.zip
* Extract it into Haxe
* Delete Haxe.zip
* Move Haxe to `~/Library/Application Support/Sublime Text 3/Packages`
* Open `~/Library/Application Support/Sublime Text 3/Packages/Haxe/Support/Hxml.sublime-build`
* Replace `haxe` with `/usr/local/bin/haxe`
* Open Sublime

Because I can. Worked like a charm.
