### ISSUE TITLE
Autocomplete not working for current class without 'this'

### ISSUE THREAD

**Issue by dana22cc** [clemos/haxe-sublime-bundle#215]
For example if I create a class extending Sprite and start writing addChild it doesn't autocomplete. But if I write this.addChild it does.

**Comment by mlopes** [comment]
I have the same issue:

![image](https://cloud.githubusercontent.com/assets/654/6997108/fbb79c34-dba5-11e4-8039-89bd516c7b6f.png)

**Comment by r3a1ay** [comment]
This feature will be available in Haxe 3.2.
Now you can use a snippet. 
`t - tab` for example:
```xml
<snippet>
	<content><![CDATA[this.]]></content>
	<tabTrigger>this</tabTrigger>
	<scope>source.haxe.2</scope>
	<description>this</description>
</snippet>
```

**Comment by clemos** [comment]
It should actually be implemented currently (if you have Haxe 3.2+)
But it doesn't seem to work, no completion is returned by the compiler, and the plugin falls back to "our" toplevel completion (local syntax based + classpaths)
https://github.com/clemos/haxe-sublime-bundle/blob/master/HaxeComplete.py#L1997-L1998
I guess in order for toplevel completion to work, we should set `offset` (or `byte_offset`) to the beginning of the current word, rather than to the current caret position, somewhere around here:
https://github.com/clemos/haxe-sublime-bundle/blob/master/HaxeComplete.py#L1985-L1986

**Comment by r3a1ay** [comment]
Yes, it seems this should help.
I planned to fix it after release. I'm still on Haxe 3.1.3.
Can you try it?

**Comment by clemos** [comment]
It should work now, please confirm.
