### ISSUE TITLE
Sometimes autocompletion fails, I don't know how to diagnose.

### ISSUE THREAD

**Issue by dionjwa** [clemos/haxe-sublime-bundle#254]
I'm using ST3 on a mac. My build.hxml is ok. Sometimes I get autocompletion working great, then sometimes later it stops working and I get the generic autocompletion offerings. I can't seem to find a pattern. I can test the autocompletion manually with the haxe terminal command and it gives me the completion data back, so I know that the code+compiler is working ok.

Do you have suggestions on where to start debugging to figure out where autocompletion is failing? Are there steps you recommend?

**Comment by dionjwa** [comment]
Maybe this:
    Starting Haxe server on port 6001
    Indexing gherkin phrases done
    Could not import subprocess32 module, falling back to subprocess module

**Comment by clemos** [comment]
Maybe the Haxe compiler (server) process crashes at some point ? 
It vaguely rings a bell, it would be worth checking that in the Haxe compiler issues.
You may try to disable `haxe_completion_server_mode` in your local settings, and see if it works better (completion will be slower, obviously, but it may last longer)

About your second comment, I don't think the error refers to the haxe bundle, but to some other ST plugin.
Maybe you could also try disabling those other plugins, in case the issue is due to friction / incompatibility with some other plugin, which is possible.
